---
title: Lab Files
format: html
---

## Research Design

> *Default*: Students are presented with the following research prompt: Professor Brocker and his colleague Dr. Khaled want to find out what exactly is 'the best music'. How can they go about studying this?

Lab 2: Operationalization

> *Default*: Students think of different ways to operationalize the concept of 'best music'.

Lab 3: Standard Deviations and Z-Scores

> *Default*: Student enters in an artist they like and calculate standard deviations for each variable item. Students use the z-score formula to determine whether any song(s) are outliers.

**Data**

Lab 4: Descriptive Statistics

> *Default*: Similar to Lab 3, students will find the Mean, Median, and Mode, and Range for select variables.

Lab 5: Hypothesis Testing

> *Default*: Hypothesis formation will be discussed and the theory-data-cycle will be used to provide students with help in creating a sound hypothesis.

Lab 6: Correlation

> *Default*: Students will discuss which variables they would hypothesize to track with one another and test this statistically.

**Data**

Lab 7: Linear Regression

**Data**

Lab 8: ANOVA

**Data**

Lab 9: Follow-up Comparisons in ANOVA

**Data**

Lab 10: Within-subjects ANOVA

**Data**

Lab 11: Reliability and Validity

**Data**

Lab 12: Results Section
