project:
  type: website
  output-dir: docs

website:
  title: "PSY348: Statistics for Psychology"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - lecture.qmd
      - lab.qmd

format:
  html:
    theme: cosmo
    css: custom.scss
    toc: true

editor: visual

